package com.jmtsu.recordLitoral.models.enums;

public enum TipoDanosVeiculo {
	PORTA_TRAS_ESQ,
	PORTA_DIANT_ESQ,
	LATERAL_TRAS_ESQ,
	PARALAMA_ESQ,
	CAPO_MOTOR,
	TETO,
	PARACHOQUE_DIANT,
	PARACHOQUE_TRAS,
	RODAS_CALOTAS,
	VIDROS_PARABRISA,
	FAROIS,
	LANTERNAS,
	ANTENA,
	BANCOS,
	PAINEL_DE_VEICULO,
	RETROVISOR,
	TAMPA_PORTA_MALA,
	PARALAMA_DIR,
	PORTA_DIAN_DIR,
	PORTA_TRAS_DIR,
	GUARDA_CHUVA,
	REPELENTE,
	PROTETOR_SOLAR,
	NULL
}
